### PR TITLE
Handle extras appearing in other rules

### LINKED ISSUE #36: mismatch ocaml-tree-sitter vs tree-sitter for Swift grammar
There are a few errors when making in ocaml-tree-sitter-semgrep:
```
$ cd lang
$ ./test-lang switft
```
3 errors seems due to the use of emoji (I've created a separate issue for that, see #35 )
The last one seems due to the parsing of multiline comments.

If you take this simple hello.swift file:
```
class foo {
    var isFailed: Bool
    /* some comment */ let foo = 1
}
```
then it seems to parse correctly with tree-sitter (it's part of the testsuite in corpus/classes.txt in a slightly more complex form)
but failed after being through the ocaml-tree-sitter machinery.

here is the error:
```
$ cd swift
$ make
$ ./parse-swift ~/hello.swift
CST obtained from the tree-sitter parser:
source_file:
| top_level_statement:
|   global_declaration:
|   | class_declaration:
|   |   modifierless_class_declaration:
|   |   | "class"
|   |   | simple_identifier:
|   |   |   pat_9d0cc04:
|   |   | class_body:
|   |   |   "{"
|   |   |   !ERROR!:
|   |   |   | possibly_async_binding_pattern_kind:
|   |   |   |   binding_pattern_kind:
|   |   |   |   | "var"
|   |   |   | !ERROR!:
|   |   |   |   single_modifierless_property_declaration:
|   |   |   |   | no_expr_pattern_already_bound:
|   |   |   |   |   bound_identifier:
|   |   |   |   |   | simple_identifier:
|   |   |   |   |   |   pat_9d0cc04:
|   |   |   |   | type_annotation:
|   |   |   |   |   ":"
|   |   |   |   |   possibly_implicitly_unwrapped_type:
|   |   |   |   |   | type:
|   |   |   |   |   |   unannotated_type:
|   |   |   |   |   |   | user_type:
|   |   |   |   |   |   |   simple_user_type:
|   |   |   |   |   |   |   | simple_identifier:
|   |   |   |   |   |   |   |   pat_9d0cc04:
|   |   |   | multiline_comment:
|   |   |   | binding_pattern:
|   |   |   |   binding_pattern_kind:
|   |   |   |   | "let"
|   |   |   |   no_expr_pattern_already_bound:
|   |   |   |   | bound_identifier:
|   |   |   |   |   simple_identifier:
|   |   |   |   |   | pat_9d0cc04:
|   |   |   | eq_custom:
|   |   |   | integer_literal:
|   |   |   | semi:
|   |   |   "}"
| semi:
---
Recovered typed CST:
|   |   Global_decl
|   |   | Class_decl
|   |   |   | Choice_class_simple_id_opt_type_params_opt_COLON_inhe_specis_opt_type_consts_class_body
|   |   |   |   | Class
|   |   |   |   | class
|   |   |   |   | Pat_9d0cc04
|   |   |   |   | foo
|   |   |   |   | "{"
|   |   |   |   | "}"
|   |   ""
total lines: 5
error lines: 3
error count: 1
success: 40.00%
Error: File /home/pad/hello.swift, line 2, character 4 to line 4, character 0:
class foo {
    var isFailed: Bool
    /* some comment */ let foo = 1
}

parent: class_body, left sibling: "{", first child: possibly_async_binding_pattern_kind
node type: ERROR
children: [
  possibly_async_binding_pattern_kind
  ERROR
  multiline_comment
  binding_pattern
  eq_custom
  integer_literal
  semi
]
Unrecognized construct
```

### PR DESCRIPTION
**Pull request by nmote**
See explanation in comments.

Fixes #36

Test plan: Automated tests

### Security

- [x] Change has no security implications (otherwise, ping the security team)

### CODE REVIEW

File: src/gen/lib/Simplify_grammar.ml [hunk 1]
```diff
@@ -151,7 +151,127 @@ let translate_named_prec_level translate_name (x : named_prec_level) =
...
+      |> Seq.map (fun (name, _) -> (name, ()))
+      |> Hashtbl.of_seq
+    in
+    fun name ->
+      if Hashtbl.mem used_rule_names name then
+        make_rule_name (name ^ "_")
+      else (
+        Hashtbl.add used_rule_names name ();
+        name
+      )
```
Comment (mjambon) [inline src/gen/lib/Simplify_grammar.ml:197]: The code above looks correct but it can be tricky if we start modifying it. The `Fresh` module will cover this. It's hard to discover, though. Maybe we should have a subfolder named `naming` or some other mechanism that helps us discover which naming techniques are already available.

File: src/gen/lib/Simplify_grammar.ml [hunk 2]
```diff
@@ -151,7 +151,127 @@ let translate_named_prec_level translate_name (x : named_prec_level) =
...
+    | FIELD (field_name, x) -> FIELD (field_name, insert_aliases x)
+    | IMMEDIATE_TOKEN x -> IMMEDIATE_TOKEN (insert_aliases x)
+    | TOKEN x -> TOKEN (insert_aliases x)
+  in
+  let rules = List.map (fun (id, body) -> (id, insert_aliases body)) grammar.rules in
+  (* Later in the pipeline, ocaml-tree-sitter-core checks that each name used in
+   * an alias is associated with an actual rule. I (nmote) suspect that this
+   * isn't necessary, but for now we'll insert a blank rule for each new alias
+   * to satisfy this check.
+   * *)
```
Comment (mjambon) [inline src/gen/lib/Simplify_grammar.ml:240]: ok, we can revisit this another time.

File: src/gen/lib/Simplify_grammar.ml [hunk 3]
```diff
@@ -151,7 +151,127 @@ let translate_named_prec_level translate_name (x : named_prec_level) =
...
+    (* Hack to work around https://github.com/tree-sitter/tree-sitter/issues/1834.
+     *
+     * Insert an unused rule that simply aliases each extra to itself, just after
+     * the entry point. This keeps tree-sitter from renaming all instances of the
+     * extra based on the alias that appears later.
+     *
+     * This hack won't work if the extra in question appears in the very first
+     * rule, since we can't insert the dummy rules before the grammar entry
+     * point. Hopefully that never happens in practice, but if it does we could
+     * likely address it using some additional transformations. *)
```
Comment (mjambon) [inline src/gen/lib/Simplify_grammar.ml:253]: :+1: epic!

**Review by mjambon — APPROVED** [review]

File: src/gen/lib/Simplify_grammar.ml (hunk 1 above)
Comment (nmote) [reply src/gen/lib/Simplify_grammar.ml:197]: Thanks! I spent a little time looking for something like this but didn't find it. I'll update this to use `Fresh`.

**Comment by nmote** [comment]
I decided to handle the case of duplicate rule names when generating a `Fresh.scope` with a `failwith` rather than propagating the `Result.t` upwards. Duplicate rule names seem fatal anyway so it seemed reasonable, but I'm happy to change this in a follow-up PR if you disagree.
